# Generated by Django 2.1 on 2018-09-09 21:37

import Myprofile.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myprofile', '0005_auto_20180907_1209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, height_field='height_field', null=True, upload_to=Myprofile.models.user_directory_path, width_field='width_field'),
        ),
    ]
