# Generated by Django 2.1 on 2018-09-09 21:42

import Myprofile.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myprofile', '0006_auto_20180910_0307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to=Myprofile.models.user_directory_path),
        ),
    ]
