# Generated by Django 2.1 on 2018-09-10 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myprofile', '0009_filee'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FILEE',
        ),
        migrations.AlterField(
            model_name='post',
            name='post',
            field=models.TextField(null=True),
        ),
    ]
