# Generated by Django 2.1 on 2018-09-08 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20180908_0910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_pic',
            field=models.ImageField(default='/media/profile.png', upload_to='dp'),
        ),
    ]
