# Generated by Django 2.1 on 2018-09-08 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20180908_0916'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='height_field',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='width_field',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='city',
            field=models.CharField(default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='description',
            field=models.CharField(default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profile_pic',
            field=models.ImageField(default='/media/profile.png', upload_to='upload_location'),
        ),
    ]
