# Generated by Django 2.1 on 2018-09-08 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20180908_0925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_pic',
            field=models.FileField(default='/media/profile.png', upload_to='upload_location'),
        ),
    ]
